### ISSUE TITLE
window scrolling on drag up or down causes cursor to lose it's position

### ISSUE THREAD

**Issue by JaneCoder** [react-grid-layout/react-draggable#151]
Hello,

I really love your projects. Thanks for these awesome frameworks. I'm actually using react-grid-layout, but my issue is in this dependent project.

I'm struggling with having large boxes to drag that require scrolling to drag vertically. The cursor loses it's position on the drag handle when scrolling and the user loses the ability to drag a card to the top, as their cursor gets to the top way before the card.

Thanks for any help with this.

PS, you can see the issue in the react-grid-layout showcase demo, but as the boxes are small, the cursor does not get that out of range. Increasing some box sizes and trying to drag large boxes with scrolling needed reveals the issue.

**Comment by STRML** [comment]
Hi @JaneCoder,

An update I pushed a few months back was built to address the issue of the window/body scrolling, but it is not yet generic enough to handle any scrollable ancestor.

At one point, a user [put together a PR](https://github.com/mzabriskie/react-draggable/pull/87/commits/4483c266540533e11277ee743460dac24d0b0600) to address this, but the project changed significantly in the meantime and the PR was closed.

**Comment by dkozar** [comment]
Actually here's how it worked in action: http://youtu.be/FZ-L5x4E02k

:-)

Danko

**Comment by JaneCoder** [comment]
Wow @dkozar that looks sweet in the video.

I have only 2 sprints left on my project  with lots left to do. And being a c/java/ruby developer who is new to javascript and react, I'm not sure I can figure out how to code a fix in time.

But @STRML's grid is just awesome. I spiked on many and this was the best. Maybe I'll burn some midnight oil this weekend and try.

**Comment by STRML** [comment]
I'm working to fix this by not simply using `clientX`, but instead referencing the `offsetParent` to get a true reading of where the cursor is relative to the draggable's parent. We'll see - some success on `body` but still working on nested scrollable divs.

**Comment by dkozar** [comment]
That is the right approach. Current position should be a cummulative of all the offests of all the scrollable parents in the hierarchy.

Just make sure that you subscribe to all of these for scroll changes ;)

Danko

**Comment by STRML** [comment]
I think it's [easier than that](https://youtu.be/bygmDAdtHz8)! Going to push to `master` shortly, try the changes yourself.

**Comment by dkozar** [comment]
Looks promising! We would also like to enjoy this patch... Thanks for the effort :)

Danko

**Comment by STRML** [comment]
@dkozar @JaneCoder Please try latest `master` - you can clone, `npm install`, `npm run build`, then `npm link` it into your project. Looks green on my end but would like to get feedback before I make a release.

**Comment by JaneCoder** [comment]
I'm still getting the cursor issue, but perhaps I'm not actually getting your changes properly, being pretty green. Is there a way I can tell if my project's version of react-grid-layout is using this version of react-draggable?

**Comment by STRML** [comment]
You'd have to npm link it into your local project and build it which can be
a little hairy. It's easier if you're using npm 3 or declaring Draggable ad
a top level dependency.

**Comment by JaneCoder** [comment]
now when I npm install react-grid-layout I'm seeing a lot of this:

npm WARN skippingAction Module is inside a symlinked module: not running remove acorn@1.2.2 node_modules/react-draggable/node_modules/acorn

**Comment by JaneCoder** [comment]
PS if it helps my grid is the responsive one, but so far I only have this one layout. Perhaps I am doing something wrong with this. 

    var layout = [
                   {i: 'a', x: 0, y: 0, w: 2, h: 4, isResizable: false},
                   {i: 'b', x: 2, y: 0, w: 2, h: 4, isResizable: false},
                   {i: 'c', x: 0, y: 0, w: 2, h: 4, isResizable: false},
                   {i: 'd', x: 2, y: 0, w: 2, h: 6, isResizable: false},
                   {i: 'e', x: 0, y: 0, w: 2, h: 4, isResizable: false},
                   {i: 'f', x: 2, y: 0, w: 2, h: 4, isResizable: false},
                   {i: 'rg, x: 0, y: 0, w: 2, h: 4, isResizable: false}
                 ];

**Comment by JaneCoder** [comment]
Any ideas on a way to tell for sure if I've got your change? I tried npm show react-grid-layout, but that did not seem to show my source.

**Comment by JaneCoder** [comment]
OK, thanks.  I really appreciate what you've done here and your willingness to jump in and address the issue. 

I'll try working on it more this weekend and hope to have some luck. Perhaps I have more than one problem; the vertical scrolling thing with my cards being so tall they fill the view height, and having links and other elements that respond to mouse-over on them. Cards appear to get stuck passing over each other on vertical drag and the cursor loses it's place.

I found in trials, that putting twitter widgets in boxes of the showcase demo causes vertical drag issues too, even when not needing the large amount of scrolling that my rather huge boxes need to drag vertically.

**Comment by JaneCoder** [comment]
It does seem to be better on vertically changing items places. I'm still seeing some drift of the cursor above or below the drag handle but it's doable to vertically drag the cards with scroll.

**Comment by STRML** [comment]
@JaneCoder @dkozar I've published this as `1.4.0-beta1` to make your testing easier.

**Comment by dkozar** [comment]
Great!

Sorry for me not being available for testing (planty of work vs sleep), but I guarantee that I'll be a number one user of the new release because the feature was really needed.

Danko

**Comment by JaneCoder** [comment]
OK, good news / bad news. I was able to confirm I got your change installed and the vertical dragging worked like a charm.

But now horizontal dragging suffers from the item dragged always trying to fly to  the top of the page, higher items in the grid popping down.  

I reverted a branch to use the old version, and horizontal is perfect. In the new version vertical is perfect.  If only the twain could meet.

I'm going to try out your beta, just in case I had some other issue with my greeness to all this. And thank you a million times for doing this.

**Comment by JaneCoder** [comment]
Ah well, I'm finding on vertical drag the cursor is still getting away from the drag handle. Not seeing the floating to the top issue on horizontal drag now. I guess that was something I accidentally introduced.

OK, back to my drawing board. Thanks for all the work.

**Comment by JaneCoder** [comment]
I'm thinking that perhaps my grid is not really a good use case for react-grid-layout. Perhaps what I need is to work on a sortable solution. I've got rather large cards stacked deep in 2 columns of cards. This requires a lot of scrolling to do vertical sort. Perhaps I'm misusing the framework?

  var layout = [
                   {i: 'a', x: 1, y: 0, w: 4, h: 10, isResizable: false},
                   {i: 'b', x: 6, y: 0, w: 4, h: 10, isResizable: false},
                   {i: 'c', x: 1, y: 11, w: 4, h: 15, isResizable: false},
                   {i: 'd', x: 6, y: 11, w: 4, h: 10, isResizable: false},
                   {i: 'e', x: 1, y: 27, w: 4, h: 10, isResizable: false},
                   {i: 'f', x: 6, y: 22, w: 4, h: 10, isResizable: false},
                   {i: 'g', x: 6, y: 33, w: 4, h: 10, isResizable: false}
                 ];

<ResponsiveReactGridLayout className="layout" layouts={this.state.layouts} 
        width={1200}
        rowHeight={43} cols={{lg: 12, md: 5, sm: 5}} >

**Comment by STRML** [comment]
@JaneCoder Could you check if your issue is resolved in `2.x`?

**Comment by JaneCoder** [comment]
Seems to be a little better. And we've made the cards being dragged much
smaller, which helped.
I'm not sure there is anything that can be done to stop the 'hold spot' on
the card from slipping away from the cursor when the page scrolls while
dragging.

It's not perfect, but doable now I think. Thank you for your help.

**Comment by STRML** [comment]
Hmm. Technically the position should be fine while the page scrolls - at least, in the demo, it is. But React-Grid-Layout is not using draggable v2 yet.

**Comment by JaneCoder** [comment]
Ah that must be it! I thought if I loaded version 2 with npm --save to
update my package.json that react-grid-layout would pick it up.
Is there a way I can force it to do that? And I can't thank you enough for
this update :)

**Comment by JaneCoder** [comment]
Demo looks great. I believe this is solved.

**Comment by STRML** [comment]
Great - I still have not updated RGL yet to v2 but am almost done with the conversion. We will enjoy quite a few bug fixes once it lands. :)

**Comment by choenes** [comment]
> Actually here's how it worked in action: http://youtu.be/FZ-L5x4E02k
> 
> :-)
> 
> Danko
> 
> > On 11.04.2016., at 22:10, Samuel Reed [notifications@github.com](mailto:notifications@github.com) wrote:
> > Hi @JaneCoder,
> > An update I pushed a few months back was built to address the issue of the window/body scrolling, but it is not yet generic enough to handle any scrollable ancestor.
> > At one point, a user put together a PR to address this, but the project changed significantly in the meantime and the PR was closed.
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub



> @JaneCoder Could you check if your issue is resolved in `2.x`?

@STRML I'm not sure what I'm missing but using 2.2.6 the demo page doesn't scroll the document if I drag a draggable off page like the youtube video links show here.

**Comment by morgs32** [comment]
I'm struggling with this too. @choenes Did you get anywhere? Maybe I could pick up where you left off?

**Comment by Spiderixius** [comment]
Heya friends. Is it possible to disable the scrolling when I drag my element to the bottom/top?
